version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/app
    expose:
      - 4000
    # uncomment if you want to do docker exec -it trio-umbrella_web_1 bash and
    # run your own command. Ie: like iex -S mix phx.server required for IEx.pry
    # command: bash -c "while [ true ]; do sleep 10; done"
    environment:
      - MIX_ENV=dev
    depends_on:
      - postgres
    networks:
      default:
        aliases:
          - application
    

  postgres:
    image: postgres
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: av_products_db
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      default:
        aliases:
          - postgres

volumes:
  pgdata:

networks:
  default: